export { ReactComponent as Css } from './css.svg'
export { ReactComponent as Html } from './html.svg'
export { ReactComponent as React } from './react.svg'
export { ReactComponent as Tailwind } from './tailwind.svg'
export { ReactComponent as Javascript } from './javascript.svg'
export { ReactComponent as Typescript } from './typescript.svg'
